train:
  dataset_path: "D:/DeepLearning/Dataset/Apple/Fuji-SfM/1-Mask-set/training_images_and_annotations"
  
validation:
  dataset_path: "D:/DeepLearning/Dataset/Apple/Fuji-SfM/1-Mask-set/validation_images_and_annotations"
  
label_type: "mask"

width: 1024
height: 1024