base_path: D:/DeepLearning/Dataset/Apple/Fuji-SfM/1-Mask-set/

train:
  dataset_path: ${dataset.base_path}/training_images_and_annotations
  files_to_exclude:
    - "_MG_7954_01"
  
validation:
  dataset_path: ${dataset.base_path}/validation_images_and_annotations
  files_to_exclude: []
  
label_type: "mask"

width: 1024
height: 1024