dataset_path: "D:/DeepLearning/Dataset/Apple/KFuji RGB-DS/preprocessed data/images"
annotation_path: "D:/DeepLearning/Dataset/Apple/KFuji RGB-DS/preprocessed data/annotations"

train:
  filelist_txt_path: "D:/DeepLearning/Dataset/Apple/KFuji RGB-DS/preprocessed data/sets/train.txt"
  files_to_exclude:
   - "BD12_sup_201711_015_05_RGB"
  
test:
  filelist_txt_path: "D:/DeepLearning/Dataset/Apple/KFuji RGB-DS/preprocessed data/sets/test.txt"

validation:
  filelist_txt_path: "D:/DeepLearning/Dataset/Apple/KFuji RGB-DS/preprocessed data/sets/val.txt"
  
label_type: "mask"

width: 1024
height: 1024