# 농촌진흥청 사과 데이터
# Korea Rural Development Administration Apple Dataset
base_path: D:/DeepLearning/Dataset/Apple/RDA_Apple

train:
  dataset_path: ${dataset.base_path}/train/images
  gt_path: ${dataset.base_path}/train/labels
  
test:
  dataset_path: ${dataset.base_path}/test/images
  gt_path: ${dataset.base_path}/test/labels
  
# [cx, cy, w, h]
label_type: "bounding box"

width: 1024
height: 1024