base_path: D:/DeepLearning/Dataset/Apple/WSU2019/CropLoadEstimation

train:
  dataset_path: ${dataset.base_path}
  gt_path: ${dataset.base_path}/Annotation.txt
  files_to_exclude:
    - "image-1"
    - "image-2"
    - "image-3"
    - "image-5"
    - "image-6"
    - "image-7"
    - "image-8"
    - "image-9"
    - "image-10"
    - "image-11"
    - "image-12"
    - "image-13"
    - "image-14"
    - "image-15"
    - "image-16"
    - "image-20"
    - "image-21"
    - "image-22"
    - "image-23"
    - "image-24"
    - "image-25"
    - "image-26"
    - "image-27"
    - "image-28"
    - "image-29"
    - "image-30"
    - "image-31"
    - "image-33"
    - "image-34"
    - "image-35"
    - "image-36"
    - "image-37"
    - "image-40"
    - "image-42"
    - "image-43"
    - "image-75"
    - "image-181"
    - "image-185"
    - "image-197"
    - "image-208"
    - "image-215"
    - "image-228"
    - "image-234"
    - "image-236"
    - "image-237"
  
label_type: "bounding box"

# 데이터 사이즈 다름
# 1494 x 1992, 2976 x 3968