base_path: D:/DeepLearning/Dataset/Apple/WSU2020

train:
  dataset_path: ${dataset.base_path}/Original RGB/Original RGB
  gt_path: ${dataset.base_path}/Original RGB XML/XML

label_type: "bounding box"

width: 1920
height: 1080